### ISSUE TITLE
mysql connection not working

### ISSUE THREAD

**Issue by iDustbin** [Dhyeythumar/Search_Engine#2]
Hi, 
i want to use your python scrappy integration.
i edited both files. server.js & Python_scripts/database_conn.py
afterwords im running: npm start

error: 
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Server is listening on port 3000!
DB connection failed

Connection to Database is working ! Any hint ? 
Best regards and thanks in advance

**Comment by iDustbin** [comment]
& is there any way to delete your user tracking ? im looking for an mostly anonymous search engine... no tracking required ! 
thanks

**Comment by dhyeythumar** [comment]
Hi @iDustbin, did you set the credential in util/database.js?

It looks like this:
https://github.com/Dhyeythumar/Search-Engine/blob/a060f0eefc4553188978b24e65049366f8db4957/util/database.js#L3-L10

And same goes for python side conection in Python_scripts/database_conn.py
https://github.com/Dhyeythumar/Search-Engine/blob/a060f0eefc4553188978b24e65049366f8db4957/Python_scripts/database_conn.py#L5-L10

**Comment by dhyeythumar** [comment]
> & is there any way to delete your user tracking ? im looking for an mostly anonymous search engine... no tracking required !
> thanks

Are you looking for production level search engine? Then I think this project is not sufficient for that, I have created this as a hobby project 😅.
